@startuml
'https://plantuml.com/activity-diagram-beta

start
:xxlJob.batchGenerate();
:批量查询商户信息;
if (商户信息存在) then (循环生成)
 if(查询商户已确认的结账单) then()
  if (isForward?) then (no)
    :Process controls;
    if (continue processing?) then (no)
      stop
    endif

    if (isPost?) then (yes)
      :Page.onPost();
    else (no)
      :Page.onGet();
    endif
    :Page.onRender();
  endif
  else (不生成)
endif
else()
endif
if (do redirect?) then (yes)
  :redirect process;
else
  if (do forward?) then (yes)
    :Forward request;
  else (no)
    :Render page template;
  endif
endif

stop

@enduml
